# Generated by Django 5.1.6 on 2025-02-24 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_reportrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportrequest',
            name='restaurant',
        ),
    ]
