# Generated by Django 5.1.6 on 2025-02-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('WAITRESS', 'Waitress'), ('OWNER', 'Owner')], default='ADMIN', max_length=10),
        ),
    ]
